-- ---------------------------------------------------------------------------
-- Propósito : Carga del catálogo de productos terminados (483 ítems) provisto
--             por la Gerencia el 2026-09-11 en productos.csv.
-- Reglas    : Ninguna nueva. §4.7 (catálogo de productos terminados).
--             Vida útil de 36 meses por indicación de la Gerencia, ver abajo.
-- Fecha     : 2026-09-11
-- ---------------------------------------------------------------------------
--
-- EL ARCHIVO TRAE DOS COLUMNAS: `codigo_interno` y `nombre`. Nada más. Así que
-- `variedad`, `tipo`, `forma_cosmetica` y `origen` quedan en NULL: no hay de
-- dónde sacarlos y no se infieren del nombre. `tipo` y `forma_cosmetica` siguen
-- siendo `text` a la espera de que un archivo fije su vocabulario, que era para
-- lo que se los había dejado sin enum; este no lo fija.
--
-- VIDA ÚTIL: 36 MESES EN LOS 483, POR INDICACIÓN DE LA GERENCIA (2026-09-11).
-- Es un valor declarado por la Gerencia, no un dato del archivo ni un cálculo.
-- Se escribe en las filas y **no** como `DEFAULT` de la columna: un default
-- haría que todo producto futuro naciera afirmando tres años de vida útil sin
-- que nadie lo haya dicho de ese producto, y la afirmación quedaría sin autor.
-- Escrito en las filas, el asiento de auditoría registra quién lo puso y cuándo.
--
-- Vale registrar la reserva: la vida útil de un producto cosmético sale de su
-- estudio de estabilidad y es por producto, no por catálogo. 36 meses parejos
-- es un provisorio razonable para arrancar, y un inspector lo va a pedir por
-- producto. Anotado como decisión abierta.
--
-- ADVERTENCIA SOBRE EL CONTENIDO DE LA LISTA. Alrededor de 108 de los 483 ítems
-- no son producto cosmético: pinceles, fresas, limas, tijeras, empujadores de
-- cutícula, dappen dishes, nail tips y exhibidores. Son herramientas, descartables
-- y material de venta. `gmp.productos` es el catálogo de producto terminado
-- alcanzado por Buenas Prácticas, y meter ahí una tijera la arrastra al circuito
-- de producción, liberación de lote y retiro de mercado. Se cargan igual porque
-- así vino la lista y porque el maestro tiene que reflejar lo que la planta
-- vende, pero **hace falta separarlos**: el candidato natural es la columna
-- `tipo`, poniendo COSMETICO / ACCESORIO cuando la Gerencia lo confirme.
-- Anotado como decisión abierta.
--
-- Dos ítems vienen marcados como discontinuados en el propio nombre («136 (No
-- se usa mas) NAIL PREP 12ML» y «138 no se usaCLARIFICADOR ( CLEANSER ) 250ML»).
-- Se cargan con `activo = true` como todos: bajarlos sería interpretar el
-- nombre, y `activo` es una decisión de la Gerencia, no una lectura de texto.
-- Anotado también.
--
-- Los nombres se transcriben tal cual vinieron, incluidos 36 que el archivo
-- trae cortados en 40 caracteres («… PARA DISE», «… Cono trunca») y uno con el
-- carácter final dañado («176 F-2 PINCEL CHATO SINTETICO N2 PARA DISEí», donde
-- iba DISEÑO). Mismo criterio que con la numeración romana de los pigmentos
-- (R-04): el nombre es la denominación del papel y la identidad la lleva
-- `codigo_interno`. Corregirlos requiere el nombre completo, que hay que pedir.
--
-- ON CONFLICT sobre `codigo_interno`, para que reaplicar no falle ni duplique.

insert into gmp.productos (codigo_interno, nombre, vida_util_meses)
select v.codigo_interno, v.nombre, 36
  from (values
  ('80', 'ROSADO TRASLUCIDO 14GRM'),
  ('81', 'ROSADO NATURAL 14GRM'),
  ('82', 'CLEAR TRANSPARENTE 14GMR'),
  ('83', 'BLANCO FRENCH 14GRM'),
  ('84', 'BLANCO SHIMMER 14GRM'),
  ('85', 'SHOW COVER PINK 14GRM'),
  ('86', 'SOFT COVER PINK 14GRM'),
  ('87', 'DARK COVER PINK 14GRM'),
  ('88', 'PINKY COVER PINK 14GRM'),
  ('89', 'COVER PINK BEIGE 14GRM'),
  ('90', 'COVER PINK DIAMONDS 14GRM'),
  ('91', 'COVER PINK PRINCESS 14GRM'),
  ('92', 'COVER PINK GOLDEN TOUCH 14GRM'),
  ('80PACK', 'PACK X6 ROSADO TRASLUCIDO 14GRM'),
  ('81PACK', 'PACK X6 ROSADO NATURAL 14GRM'),
  ('82PACK', 'PACK X12 CLEAR TRANSPARENTE 14GMR'),
  ('83PACK', 'PACK X12 BLANCO FRENCH 14GRM'),
  ('84PACK', 'PACK X6 BLANCO SHIMMER 14GRM'),
  ('85PACK', 'PACK X12 SHOW COVER PINK 14GRM'),
  ('86PACK', 'PACK X12 SOFT COVER PINK 14GRM'),
  ('87PACK', 'PACK X12 DARK COVER PINK 14GRM'),
  ('88PACK', 'PACK X6 PINKY COVER PINK 14GRM'),
  ('89PACK', 'PACK X6 COVER PINK BEIGE 14GRM'),
  ('90PACK', 'PACK X6 COVER PINK DIAMONDS 14GRM'),
  ('91PACK', 'PACK X6 COVER PINK PRINCESS 14GRM'),
  ('92PACK', 'PACK X6 COVER PINK GOLDEN TOUCH 14GRM'),
  ('93', 'ROSA TRASLUCIDO 45GRM'),
  ('94', 'ROSADO NATURAL 45GRM'),
  ('95', 'CLEAR TRANSPARENTE 45GRM'),
  ('96', 'BLANCO FRENCH 45GRM'),
  ('97', 'BLANCO SHIMMER 45GRM'),
  ('98', 'SHOW COVER PINK 45GRM'),
  ('99', 'SOFT COVER PINK 45GRM'),
  ('100', 'DARK COVER PINK 45GRM'),
  ('93PACK', 'PACK X8 ROSA TRASLUCIDO 45GRM'),
  ('94PACK', 'PACK X8 ROSADO NATURAL 45GRM'),
  ('95PACK', 'PACK X12 CLEAR TRANSPARENTE 45GRM'),
  ('96PACK', 'PACK X12 BLANCO FRENCH 45GRM'),
  ('97PACK', 'PACK X8 BLANCO SHIMMER 45GRM'),
  ('98PACK', 'PACK X12 SHOW COVER PINK 45GRM'),
  ('99PACK', 'PACK X12 SOFT COVER PINK 45GRM'),
  ('100PACK', 'PACK X12 DARK COVER PINK 45GRM'),
  ('101', 'MONOMERO 100ML'),
  ('102', 'MONOMERO 250ML'),
  ('103', 'MONOMERO 500ML'),
  ('105', 'PRIMER 8ml.'),
  ('106', 'BONDER 8ml.'),
  ('107', 'GEL CONSTRUCCIÓN PINK 45GRM'),
  ('108', 'GEL CONSTRUCCIÓN ULTRA WHITE 45GRM'),
  ('109', 'GEL CONSTRUCCIÓN DARK COVER PINK 45GRM'),
  ('110', 'GEL CONSTRUCCION CLEAR 45GRM'),
  ('111', 'COLECCION DONUTS'),
  ('112', 'COLECCION MACARRONS'),
  ('113', 'COLECCION CUPCAKES'),
  ('114', 'COLECCION CHOCOLAR'),
  ('115', 'COLECCION TARTAS'),
  ('116', 'COLECCION PASTEL'),
  ('117', 'COLECCION BABY POPCAKE'),
  ('118', 'COLECCION DE GLITTERS TOPPINGS I'),
  ('119', 'COLECCION DE GLITTERS TOPPINGS II'),
  ('278', 'COLECCION LOLLIPOP'),
  ('279', 'COLECCION CANDYTOPIA'),
  ('299', 'COLECCION SMOOTHIES'),
  ('327', 'COLECCION BASICS'),
  ('120', 'COLORES INDIVIDUALES DE POLIMERO'),
  ('121', 'ACCESORIOS ( VARIOS EN STOCK)'),
  ('122', 'GEL PAINT BLANCO'),
  ('123', 'GEL PAINT NEGRO'),
  ('124', 'GEL PAINT PLATEADO'),
  ('125', 'GEL PAINT AMARILLO'),
  ('126', 'GEL PAINT FUCCIA'),
  ('127', 'GEL PAINT ROJO'),
  ('128', 'GEL PAINT VERDE'),
  ('129', 'GEL PAINT AZUL'),
  ('130', 'TOP COAT UV/LED'),
  ('131', 'ACEITE DE CUTICULAS 10ml.'),
  ('132', 'CREMA HIDRATANTE'),
  ('133', 'CREMA EXFOLIANTE'),
  ('134', 'MASCARA DE GERMEN DE TRIGO'),
  ('135', 'SANITIZANTE CON GATILLO 200ML'),
  ('136', '(No se usa mas) NAIL PREP 12ML'),
  ('137', 'ADHESIVO FOIL 1Oml.'),
  ('138', 'no se usaCLARIFICADOR ( CLEANSER ) 250ML'),
  ('139', 'KIT PINTURA ACRILICA X 12UNIDADES'),
  ('140', 'KIT PINTURA ACRILICA X 27 UNIDADES'),
  ('142', 'PIGMENTO I negro'),
  ('143', 'PIGMENTO II blanco'),
  ('144', 'PIGMENTO III ROSA'),
  ('145', 'PIGMENTO IV CELESTE'),
  ('146', 'PIGMENTO V COBRE'),
  ('147', 'PIGMENTO VI TURQUESA'),
  ('148', 'PIGMENTO VII ROSA OSCURO'),
  ('149', 'PIGMENTO VIII AZUL'),
  ('150', 'PIGMENTO IX BRONCE OSCURO'),
  ('151', 'PIGMENTO X ROSA NEON'),
  ('152', 'PIGMENTO XI VERDE NEON'),
  ('153', 'PIGMENTO XII NARANJA NEON'),
  ('154', 'PIGMENTO XIII MAGENTA NEON'),
  ('155', 'PIGMENTO XIV AMARILLO NEON'),
  ('156', 'PIGMENTO XV AZUL OSCURO'),
  ('157', 'PIGMENTO XVI VERDE OSCURO'),
  ('158', 'PIGMENTO XVII VIOLETA'),
  ('159', 'PIGMENTO XVIII NARANJA'),
  ('160', 'PIGMENTO XIX DORADO'),
  ('161', 'PIGMENTO XX ORO'),
  ('162', 'PIGMENTO XXI PLATA'),
  ('163', 'PIGMENTO XXII VIOLETA OSCURO'),
  ('164', 'PIGMENTO XXIII SALMON NEON'),
  ('165', 'PIGMENTO XXIV VERDE MANZANA'),
  ('166', 'SUGGAR XL DORADO LAME'),
  ('166PACK', 'SUGGAR XL Dorado lamé Pack x 12 unid.'),
  ('167', 'SUGGAR XLI TORNASOL EFECTO VERDE/ROSA'),
  ('168', 'SUGGAR XLII TRANSPARENTE'),
  ('169', 'ACCESORIO FOIL'),
  ('1702017', 'monomero premium 100ml'),
  ('1702018', 'POLIMERO 500GRM'),
  ('171', 'GEL PAINT DORADO'),
  ('173', 'O-8 Pincel de Practica para Esculp NUEVO'),
  ('174', 'F-7 PINCEL CHATO KOLINSKY N7 PARA GEL'),
  ('175', 'F-4 PINCEL CHATO KOLINSKY N4 PARA DISEÑO'),
  ('176', 'F-2 PINCEL CHATO SINTETICO N2 PARA DISEí'),
  ('177', 'R-4 PINCEL REDONDO KOLINSKY N4 PARA DISE'),
  ('178', 'R-3 PINCEL REDONDO SINTETICO N3 PARA DIS'),
  ('179', 'R-2 PINCEL REDONDO KOLINSKY N2 PARA DISE'),
  ('180', 'R-0 PINCEL LINER SINTETICO N0'),
  ('181', 'DT DOTTING TOOL, PUNZON DOBLE PUNTA'),
  ('197', 'PINTURAS ACRILICAS SUELTAS'),
  ('198', 'DELANTAL NAIL SHOW'),
  ('199', 'GORRA NAIL SHOW'),
  ('217', 'ACCESORIO VIP'),
  ('231', 'LIMA 100/100'),
  ('232', 'LIMA 150/150'),
  ('233', 'LIMA 180/180'),
  ('234', 'LIMA/BUFFER 180/180'),
  ('235', 'LIMA/BUFFER 100/180'),
  ('236', 'BUFFER 100/180'),
  ('237', 'BUFFER 220/280'),
  ('238', 'LIMA SHINNER DE BRILLO'),
  ('240', 'QUIMICA APLICADA PARA UÑAS'),
  ('241', 'ENFERMEDADES DE MANOS Y PIES'),
  ('242', 'CARA A CARA DE DOUG SCHOON VOLUMEN 1'),
  ('245', 'PIGMENTO VIOLETA FLUOR'),
  ('246', 'PIGMENTO CELESTE FLUOR'),
  ('247', 'PIGMENTO XXX BLANCO MATE'),
  ('247PACK', 'PIGMENTO XXX blanco mate. PACK x 12 unid'),
  ('248', 'Muestras aceite de torno x20u + tarjetas'),
  ('249', 'MUESTRA REGALO ACEITE AMOR 5cc'),
  ('249PACK', 'PACK X20 MUESTRA REGALO ACEITE AMOR 5cc'),
  ('251', 'FLAKE FUEGO INDIVIDUAL'),
  ('251PACK', 'PACK X12 GLITTER FLAKE'),
  ('252', 'PIGMENTO XXXI NEGRO MATE'),
  ('252PACK', 'PACK X12 PIGMENTO XXXI NEGRO MATE'),
  ('253', 'PIGMENTO AURORA COBRE'),
  ('254', 'PIGMENTO AURORA AZUL'),
  ('255', 'PIGMENTO AURORA ROSE'),
  ('259', 'MICROPERLAS BLANCO 0.5'),
  ('260', 'MICROPERLAS NEGRO 0.5'),
  ('261', 'MICROPERLAS COBRE 0.5'),
  ('262', 'MICROPERLAS DORADO 0.5'),
  ('264', 'REMERAS NAIL SHOW'),
  ('265', 'MICROPERLAS COBRE 1.0'),
  ('266', 'MICROPERLAS NEGRO 1.0'),
  ('267', 'MICROPERLAS BLANCO 0.8'),
  ('268', 'MICROPERLAS NEGRO 0.8'),
  ('269', 'MICROPERLAS COBRE 0.8'),
  ('270', 'MICROPERLAS DORADO 0.8'),
  ('271', 'MICROPERLAS NEGRO 0.6'),
  ('272', 'MICROPERLAS COBRE 0.6'),
  ('273', 'MICROPERLAS DORADO 0.6'),
  ('274', 'MICROPERLAS NEGRO 0.4'),
  ('275', 'MICROPERLAS BLANCO 0.4'),
  ('276', 'MICROPERLAS DORADO 0.4'),
  ('277', 'MICROPERLAS COBRE 0.4'),
  ('336', 'MICROPERLAS BLANCO 0.6'),
  ('337', 'MICROPERLAS DORADO 1.0'),
  ('338', 'MICROPERLAS BLANCO 1.0'),
  ('280', 'GEL DE CONSTRUCCION 14gr PINK'),
  ('281', 'GEL DE CONSTRUCCION 14gr. ULTRA WHITE'),
  ('282', 'GEL DE CONSTRUCCION 14gr. CLEAR'),
  ('283', 'SUGGAR COLORES'),
  ('287', 'SUGGAR XLIII TORNASOL EFECTO VIOLETA'),
  ('288', 'SUGGAR XLIV TORNASOL EFECTO VERDE/ROSA'),
  ('289', 'SUGGAR XLV TORNASOL EFECTO VIOLETA X-FIN'),
  ('290', 'SUGGAR XLVI TURQUESA'),
  ('291', 'SUGGAR XLVII VERDE NEON'),
  ('292', 'SUGGAR XLVIII AMARILLO NEON'),
  ('293', 'SUGGAR XLIX NARANJA NEON'),
  ('294', 'SUGGAR L FUCSIA NEON'),
  ('295', 'SUGGAR LI ROSA NEON'),
  ('296', 'SUGGAR LII VIOLETA'),
  ('297', 'SUGGAR LIII NEGRO'),
  ('632PACK', 'PACK x 75 Unid. 25 ACCESORIOS (3 de c/u)'),
  ('633PACK', 'PACK x 45 Unid. 15 SUGGAR (3 de c/u)'),
  ('300', 'ACCESORIOS XLVIII Plata Fino'),
  ('301', 'ACCESORIOS XLVII Plata'),
  ('302', 'ACCESORIOS XLVI Oro'),
  ('303', 'ACCESORIOS XLV Plata octogonal'),
  ('304', 'ACCESORIOS XLIV Oro tornasol'),
  ('305', 'ACCESORIOS XLIII Plata tornasol'),
  ('306', 'ACCESORIOS XLII Negro octogonal tornasol'),
  ('307', 'ACCESORIOS XLI Plata octogonal tornasol'),
  ('308', 'ACCESORIOS XL Champagne octogonal'),
  ('309', 'ACCESORIOS XXXIX Fucsia octogonal'),
  ('310', 'ACCESORIOS XXXVIII Azul octogonal'),
  ('311', 'ACCESORIOS XXXVII Glitter Turquesa Torn.'),
  ('312', 'ACCESORIOS LASSER XXXVI Glitter fucsia'),
  ('313', 'ACCESORIOS LASSER XXXV Violeta'),
  ('314', 'ACCESORIOS LASSER XXXIV Azul'),
  ('315', 'ACCESORIOS LASSER XXXIII Turquesa'),
  ('316', 'ACCESORIOS LASSER XXXII Rosa'),
  ('317', 'ACCESORIOS LASSER XXXI Magenta'),
  ('318', 'ACCESORIOS LASSER XXX Plata'),
  ('319', 'ACCESORIOS LASSER XXIX Negro'),
  ('320', 'SANITIZANTE 200ML SIN GATILLO'),
  ('321', 'TOALLA NAIL SHOW'),
  ('323', 'MONOMERO PREMIUN 1LT.'),
  ('324', 'ALMOHADON NAIL SHOW'),
  ('325', 'PORTA LIMAS'),
  ('326', 'CARTEL PUNTO DE VENTA NAIL SHOW'),
  ('328', 'PIGMENTO XXV CAMALEON LILA'),
  ('329', 'PIGMENTO XXVI COBRE ANARANJADO'),
  ('330', 'PIGMENTO XXVII COBRE ROJIZO'),
  ('331', 'ACCESORIOS LASSER XXVIII Cobre'),
  ('332', 'ACCESORIOS LASSER XXVII Verde'),
  ('333', 'ACCESORIOS LASSER XXVI Oro'),
  ('334', 'ACCESORIOS LASSER XXV Celeste Oscuro'),
  ('335', 'SANITIZANTE 1LT.'),
  ('339', 'O-8 Pincel Profesional para Esculp NUEVO'),
  ('340', 'ACEITE PARA TORNO'),
  ('342', 'LAMPARA LED'),
  ('343', 'Fsa Abras Delic p/ remocion de esmaltado'),
  ('344', 'Fsa Abras Fina p/ Remosion de esmaltado'),
  ('345', 'Fsa. Abras Media p/ Remosion de esmaltad'),
  ('346', 'Fsa Abras Gr p/ corte o Remosion esculp.'),
  ('347', 'Fsa Abras Gr p/ corte o Remosion esculp.'),
  ('348', 'Fresa Abras Media p/ Perfilar superficie'),
  ('349', 'Fsa Gramaje Grueso de Diamante cilindri'),
  ('350', 'Fsa Gramaje Medio de Diamante cilindrica'),
  ('351', 'Fsa Gramaje Fino Diamante cilindrico Peq'),
  ('352', 'Fresa Gramaje Fino de Diamante Cono'),
  ('353', 'Fresa Gramaje Medio Diamante Cono trunca'),
  ('354', 'Fresa Gramaje Fino Diamante Cilindrico'),
  ('355', 'KIT INICIAL DE ACRILICO'),
  ('356', 'Fsa suave para extraer callos profundos'),
  ('357', 'Fsa p/ extraer callos profundos dentada.'),
  ('358', 'Fsa p/ remoc de prod esculpido ext abras'),
  ('359', 'Fsa Abras Media p/ Remocion de esculpido'),
  ('360', 'LIMA 220/220'),
  ('361', 'TAPA NEGRA PARA PINCEL'),
  ('362', 'TAPA GRIS PARA PINCEL'),
  ('363', 'BOLSITO NAIL SHOW PARA KIT'),
  ('364', 'EXFOLIANTE AMOR 240ml.'),
  ('365', 'EXFOLIANTE AIRE 240ml.'),
  ('366', 'EXFOLIANTE PAZ 240ml.'),
  ('367', 'EXFOLIANTE AMOR 100ml.'),
  ('368', 'EXFOLIANTE AIRE 100ml.'),
  ('369', 'EXFOLIANTE PAZ 100ml.'),
  ('370', 'HUMECTANTE AMOR 240ml.'),
  ('371', 'HUMECTANTE AIRE 240ml.'),
  ('372', 'HUMECTANTE PAZ 240ml.'),
  ('373', 'HUMECTANTE AMOR 100ml.'),
  ('374', 'HUMECTANTE AIRE 100ml.'),
  ('375', 'HUMECTANTE PAZ 100ml.'),
  ('376', 'ACEITE PARA TORNO MUESTRA'),
  ('377', 'PREP 8ml. (NUEVO)'),
  ('378', 'Aceite de Cuticula AMOR 33ml.'),
  ('379', 'Aceite de Cuticula AIRE 33ml.'),
  ('380', 'Aceite de Cuticula PAZ 33ml.'),
  ('381', 'Aceite de Cuticula AMOR 8ml.'),
  ('382', 'Aceite de Cuticula AIRE 8ml.'),
  ('383', 'Aceite de Cuticula PAZ 8ml.'),
  ('384', 'CLARIFICADOR ( CLEANSER ) 100ml.'),
  ('385', 'CLARIFICADOR ( CLEANSER ) 250ml. (NUEVO)'),
  ('386', 'CLARIFICADOR ( CLEANSER ) 1L.'),
  ('387', 'PRIMER ACIDO NUEVO'),
  ('388', 'EXHIBIDOR DE PIE COMPLETO'),
  ('389', 'POLIMERO INDIVIDUAL STARDUST'),
  ('391', 'SANITIZANTE AMOR 200ml. (Con Gatillo)'),
  ('392', 'SANITIZANTE AMOR 125ml.'),
  ('393', 'SANITIZANTE AIRE 200ml. (Con Gatillo)'),
  ('394', 'SANITIZANTE AIRE 125ml.'),
  ('395', 'SANITIZANTE PAZ 200ml. (Con Gatillo)'),
  ('396', 'SANITIZANTE PAZ 125ml.'),
  ('397', 'KIT GEL NAIL SHOW'),
  ('398', 'KIT NAIL ART NAIL SHOW'),
  ('399', 'BOLSA NAIL SHOW'),
  ('406', 'Paleta Chica para pintura'),
  ('407', 'Paleta Grande para pintura'),
  ('411', 'Corta cutículas premium profesional 3mm'),
  ('412', 'Corta cutículas premium profesional 5mm'),
  ('413', 'Corta cutículas premium profesional 7mm'),
  ('414', 'Corta cutículas profesional 3mm'),
  ('415', 'Corta cutículas profesional 5mm'),
  ('416', 'Corta cutículas profesional 7mm'),
  ('417', 'CORTA CUTICULAS'),
  ('418', 'ALICATE PARA ESCULPIDO'),
  ('419', 'corta cuticulas mini mini'),
  ('420', 'Alicate para uñas'),
  ('421', 'Empuj de cutíc profesional redondo-punta'),
  ('422', 'Empuj de cutíc profesional angular-recto'),
  ('423', 'Empujador de cutículas Cuchara/Navaja 2'),
  ('424', 'Empujador de cutículas cuchara frontal'),
  ('431', 'Tijera para Manicuría Profesional 21mm'),
  ('432', 'Tijera para Manicuría Profesional 18mm'),
  ('433', 'Tijera en punta fina curva para moldes'),
  ('434', 'Tijera resorte en punta fina curva molde'),
  ('441', 'Pinza recta'),
  ('442', 'Pinza en forma de V'),
  ('448', 'Especimetro para uñas'),
  ('449', 'KIT COMPLETO DE 10 HERRAMIENTAS'),
  ('450', 'STARDUST BLUE 5 GR'),
  ('451', 'STARDUST GREEN 5GR'),
  ('452', 'STARDUST PINK 5GR'),
  ('453', 'STARDUST LILA 5GR'),
  ('454', 'STARDUST SILVER 5GR'),
  ('455', 'STARDUST SUN 5GR'),
  ('456', 'COLECCION POLIMERO STARDUST'),
  ('457', 'STARDUST COVER 14GR'),
  ('458', 'STARDUST COVER 45GR'),
  ('459', 'STARDUST COVER 125gr.'),
  ('460', 'STARDUST SOFT WHITE 14GR'),
  ('461', 'STARDUST SOFT WHITE 45GR'),
  ('462', 'STARDUST SOFT WHITE 125gr.'),
  ('463', 'STARDUST CLEAR 14GR'),
  ('464', 'STARDUST CLEAR 45GR'),
  ('465', 'STARDUST CLEAR 125 gr'),
  ('470', 'N-6 Pincel Aplicador Redondo Angular'),
  ('471', 'R-1 Pincel Corto Sintetico Fino'),
  ('472', 'R-0 Pincel Corto Sintetico Fino'),
  ('473', 'RL-0 Pincel Liner Sint Redond Extra Fino'),
  ('474', 'R-Micro-0 Pincel Micro Liner Sintetico'),
  ('475', 'R-000 Pincel Liner Sint Redond Extr Fino'),
  ('476', 'Kit Pinceles Nuevos + Lata grande'),
  ('481', 'Clear nail clip 3.1cm (24pcs)'),
  ('482', 'Clear nail clip 3.8cm (24pcs)'),
  ('483', 'Palitos de curva C con ejes y medidas x6'),
  ('501', 'PACK MICROPERLAS x 60 Unid. (3 c/unid.)'),
  ('502', 'Dappen dish porcelana blanco tapa corcho'),
  ('503', 'Porta herramientas plegable tornasol'),
  ('504', 'Porta herramientas plegables negro'),
  ('505', 'Porta pinceles rosa tubo Matelasse'),
  ('506', 'Porta pinceles negro tubo'),
  ('507', 'Dappen dish flor c/ tapa diamante aurora'),
  ('508', 'Dappen dish flor c/ tapa diamante plata'),
  ('509', 'Dappen dish flor c/ tapa diamante negro'),
  ('513', 'Tips Naturales XXL - Uñas Extremas'),
  ('514', 'PEGAMENTO PARA TIPS NUEVO'),
  ('514PACK', 'PEGAMENTO PARA TIPS PACK X12 Unid.'),
  ('515', 'SoftBond adhesivo para soft tips'),
  ('517', 'Nail Tips Clear Coffin-Soft Gel (M)x500u.'),
  ('519', 'Nail Tips Clear Oval-Soft Gel (M)x500u.'),
  ('520', 'Nail Tips Clear Oval-Soft Gel (S)x500u.'),
  ('521', 'Nail Tips Clear Square-Soft Gel (L)x500u.'),
  ('522', 'Nail Tips Clear Square-Soft Gel (M)x500u.'),
  ('523', 'Nail Tips Clear Square-Soft Gel (S)x500u.'),
  ('524', 'Nail Tips Clear Stiletto-Soft Gel x 500u.'),
  ('525', 'Nail Tips Clear Almendra-Soft Gel(M)x500.'),
  ('526', 'Nail Tips Clear Almendra-Soft Gel(S)x500.'),
  ('548', 'Nail tips Clear Curva C x 500Unid. + 100 Unid. De Regalo!'),
  ('NST-516', 'Nail Tips Clear Coffin-Soft Gel (S)x100u.'),
  ('NST-517', 'Nail Tips Clear Coffin-Soft Gel (M)x100u.'),
  ('NST-511', 'Nail Tips Clear Coffin-soft gel (L)x 100u.'),
  ('NST-510', 'Nail Tips Clear Oval-soft gel (L)x 100u.'),
  ('NST-519', 'Nail Tips Clear Oval-Soft Gel (M)x100u.'),
  ('NST-520', 'Nail Tips Clear Oval-Soft Gel (S)x100u.'),
  ('NST-521', 'Nail Tips Clear Square-Soft Gel (L)x100u.'),
  ('NST-522', 'Nail Tips Clear Square-Soft Gel (M)x100u.'),
  ('NST-523', 'Nail Tips Clear Square-Soft Gel (S)x100u.'),
  ('NST-524', 'Nail Tips Clear Stiletto-Soft Gel x 100u.'),
  ('NST-525', 'Nail Tips Clear Almendra-Soft Gel(M)x100u.'),
  ('NST-526', 'Nail Tips Clear Almendra-Soft Gel(S)x100u.'),
  ('NST-548', 'Nail tips Clear Curva C x 50u + Nail tips Natural Curva C x 50u.'),
  ('550', 'Mueble exhibidor Nail Show'),
  ('600', 'ALA DE ANGEL PACK x 12 Unid.'),
  ('600PACK', 'ALA DE ANGEL PACK x 36 Unid.'),
  ('601', 'ALA DE ANGEL NARANJA N°1'),
  ('602', 'ALA DE ANGEL SALMÓN N°2'),
  ('603', 'ALA DE ANGEL AMARILLO NEÓN N°3'),
  ('604', 'ALA DE ANGEL ROSA N°4'),
  ('605', 'ALA DE ANGEL FUCSIA N°5'),
  ('606', 'ALA DE ANGEL CELESTE PASTEL N°6'),
  ('607', 'ALA DE ANGEL LILA N°7'),
  ('608', 'ALA DE ANGEL VERDE N°8'),
  ('609', 'ALA DE ANGEL COBRE N°9'),
  ('610', 'ALA DE ANGEL AMARILLO N°10'),
  ('611', 'ALA DE ANGEL CELESTE N°11'),
  ('612', 'ALA DE ANGEL AZUL N°12'),
  ('613', 'Coleccion Pigmento Aurora x 12 Unidades'),
  ('614', 'Coleccion Suggar Reflectivos x 7 Unidades'),
  ('700', 'PACK P.O.P'),
  ('701', 'BOLSA DE CARAMELOS OCEAN'),
  ('702', 'ALFOMBRA NAIL SHOW GRIS'),
  ('703', 'ALFOMBRA NAIL SHOW NEGRA'),
  ('704', 'EXHIBIDORES STARDUST COVER (OCEAN)'),
  ('705', 'EXHIBIDORES STARDUST SOFT WHITE (OCEAN)'),
  ('706', 'EXHIBIDORES STARDUST CLEAR (OCEAN)'),
  ('707', 'CARTEL PROMOCIONAL MES DEL AMOR'),
  ('708', 'BOLSA ECOLOGICA NAIL SHOW'),
  ('709', 'EXHIBIDOR de herramientas pared'),
  ('710', 'Exhibidor de herramienta chico linea caj'),
  ('711', 'EXHIBIDOR de herramientas mini mini'),
  ('712', 'EXHIBIDOR COLECCION DRAGON STARDUST'),
  ('713', 'PACK P.O.P STARDUST'),
  ('715', 'Estacion de prueba de Manicure Care'),
  ('DUO01', 'PREP + PRIMER LOW'),
  ('DUO02', 'PREP + PRIMER ACIDO'),
  ('NSK-01', 'Kit Manicuría Básico'),
  ('NSK-02', 'Kit Manicuría Premium'),
  ('NSK-03', 'KIt Manicuría con Torno'),
  ('NSK-04', 'KIt Manicuría con Torno Premium'),
  ('NSK-05', 'Kit Inicial Acrílico Clásico'),
  ('NSK-06', 'Kit Inicial Acrílico Premium'),
  ('NSK-07', 'Kit Inicial Acrílico Stardust'),
  ('NSK-08', 'Kit Inicial Acrílico Stardust Premium'),
  ('NSK-09', 'Kit Manicuría Premium Alternativo'),
  ('NSK-20', 'Kit Nail Art Especial'),
  ('POL01', 'POLIMERO BASICS ROJO'),
  ('POL02', 'POLIMERO BASICS NEGRO'),
  ('POL03', 'POLIMERO BASICS AMARILLO'),
  ('POL04', 'POLIMERO BASICS MAGENTA'),
  ('POL05', 'POLIMERO BASICS AZUL'),
  ('POL06', 'POLIMERO BASICS VERDE'),
  ('POL07', 'POLIMERO DONUTS ROSA'),
  ('POL08', 'POLIMERO DONUTS MAGENTA'),
  ('POL09', 'POLIMERO DONUTS VERDE'),
  ('POL10', 'POLIMERO DONUTS AMARILLO'),
  ('POL11', 'POLIMERO DONUTS NARANJA'),
  ('POL12', 'POLIMERO DONUTS ROJO'),
  ('POL13', 'POLIMERO PASTEL ROSA'),
  ('POL14', 'POLIMERO PASTEL SALMON'),
  ('POL15', 'POLIMERO PASTEL VERDE'),
  ('POL16', 'POLIMERO PASTEL AMARILLO'),
  ('POL17', 'POLIMERO PASTEL CELESTE'),
  ('POL18', 'POLIMERO PASTEL VIOLETA'),
  ('POL19', 'POLIMERO BABYPOPCAKE DORADO'),
  ('POL20', 'POLIMERO BABYPOPCAKE FUCSIA'),
  ('POL21', 'POLIMERO BABYPOPCAKE CELESTE'),
  ('POL22', 'POLIMERO BABYPOPCAKE CONFETTI'),
  ('POL23', 'POLIMERO BABYPOPCAKE TURQUESA'),
  ('POL24', 'POLIMERO BABYPOPCAKE ROMBOS'),
  ('POL25', 'POLIMERO SMOOTHIE ROSA'),
  ('POL26', 'POLIMERO SMOOTHIE FUCSIA'),
  ('POL27', 'POLIMERO SMOOTHIE AMARILLO'),
  ('POL28', 'POLIMERO SMOOTHIE DORADO'),
  ('POL29', 'POLIMERO SMOOTHIE VERDE'),
  ('POL30', 'POLIMERO SMOOTHIE LILA'),
  ('POL31', 'POLIMERO LOLLYPOP SALMON'),
  ('POL32', 'POLIMERO LOLLYPOP FUCSIA'),
  ('POL33', 'POLIMERO LOLLYPOP BLANCO'),
  ('POL34', 'POLIMERO LOLLYPOP VERDE IRIDISCENTE'),
  ('POL35', 'POLIMERO LOLLYPOP VERDE'),
  ('POL36', 'POLIMERO LOLLYPOP ROSA'),
  ('POL37', 'POLIMERO CUPCAKE VIOLETA'),
  ('POL38', 'POLIMERO CUPCAKE SALMON'),
  ('POL39', 'POLIMERO CUPCAKE VIOLETA OSCURO'),
  ('POL40', 'POLIMERO CUPCAKE VERDE'),
  ('POL41', 'POLIMERO CUPCAKE ROSA'),
  ('POL42', 'POLIMERO CUPCAKE ROJO'),
  ('POL43', 'POLIMERO CANDYTOPIA ROSA NEON'),
  ('POL44', 'POLIMERO CANDYTOPIA MAGENTA NEON'),
  ('POL45', 'POLIMERO CANDYTOPIA VIOLETA NEON'),
  ('POL46', 'POLIMERO CANDYTOPIA NARANJA NEON'),
  ('POL47', 'POLIMERO CANDYTOPIA AMARILLO NEON'),
  ('POL48', 'POLIMERO CANDYTOPIA VERDE OSCURO NEON'),
  ('POL49', 'POLIMERO CHOCOLAT DORADO'),
  ('POL50', 'POLIMERO CHOCOLAT NEGRO'),
  ('POL51', 'POLIMERO CHOCOLAT GRIS'),
  ('POL52', 'POLIMERO CHOCOLAT ROSA'),
  ('POL53', 'POLIMERO CHOCOLAT COBRE ROJIZO'),
  ('POL54', 'POLIMERO CHOCOLAT COBRE'),
  ('POL55', 'POLIMERO MACARRONS VIOLETA'),
  ('POL56', 'POLIMERO MACARRONS VERDE'),
  ('POL57', 'POLIMERO MACARRONS TURQUESA'),
  ('POL58', 'POLIMERO MACARRONS ROSA'),
  ('POL59', 'POLIMERO MACARRONS SALMÓN'),
  ('POL60', 'POLIMERO MACARRONS ROSA NEÓN'),
  ('POL61', 'POLIMERO TARTAS AZUL'),
  ('POL62', 'POLIMERO TARTAS MAGENTA'),
  ('POL63', 'POLIMERO TARTAS ROJO'),
  ('POL64', 'POLIMERO TARTAS CELESTE'),
  ('POL65', 'POLIMERO TARTAS COBRE ANARANJADO'),
  ('POL66', 'POLIMERO TARTAS DORADO CLARO'),
  ('192', 'removedor de 120ml')
  ) as v(codigo_interno, nombre)
on conflict (codigo_interno) do nothing;
